export const DEVELOPMENT_SERVER_URL = 'http://localhost:5000/api/v1';
export const STREAMING_RESOURCE_GH_TOKEN_KEY = 'STREAMING_RESOURCE_GH_TOKEN_KEY';
export const STREAMING_RESOURCE_GH_DATA_KEY = 'STREAMING_RESOURCE_GH_DATA_KEY';